#!/bin/bash -eu
# This is a simple build script and will be executed on your CI system if available. 
# Otherwise it will execute while your application is stopped before the deploy step. 
# This script gets executed directly, so it could be python, php, ruby, etc.



# checkout the code
cd $OPENSHIFT_DATA_DIR
rm -rf europrices/
git clone ~/git/europrices.git/

# build the sources
cd europrices
mvn clean install -DskipTest -P openshift

