#!/bin/bash
BASEDIR=$OPENSHIFT_DEPLOYMENTS_DIR/current/repo/
cd $BASEDIR
mvn --global-settings $BASEDIR/.openshift/mvn-settings.xml clean install -DskipTests=true
cd $(ls -a | grep webapp)
mvn --global-settings $BASEDIR/.openshift/mvn-settings.xml install assembly:single -DskipTests=true -Popenshift -Dspecific
ARCHIVE=$(ls target | grep .tar.gz)
mv target/$ARCHIVE $OPENSHIFT_DATA_DIR
cd $OPENSHIFT_DATA_DIR
rm -rf $OPENSHIFT_DATA_DIR/europrices
tar -xvf $ARCHIVE
rm $ARCHIVE
cd $OPENSHIFT_DEPLOYMENTS_DIR/current/repo/