#!/bin/bash -xv
touch $OPENSHIFT_LOG_DIR/startstop.log
echo "$(TZ='Europe/Rome' date --rfc-3339=seconds) - start" >> $OPENSHIFT_LOG_DIR/startstop.log 
SECRETS="file://$OPENSHIFT_DATA_DIR/conf/secrets.xml"
nohup java -Dsecrets=$SECRETS -cp "$OPENSHIFT_DATA_DIR/europrices/lib/*:$OPENSHIFT_DATA_DIR/europrices/conf" com.danidemi.europrice.EuroPricesWebApp prod &> /dev/null &
