#!/bin/bash
#v0001
SECRETS=$OPENSHIFT_DATA_DIR/conf/secrets.xml
nohup java -Dsecrets=file:$SECRETS -cp "$OPENSHIFT_DATA_DIR/lib/*:$OPENSHIFT_DATA_DIR/conf" com.danidemi.europrice.EuroPricesWebApp prod &> /dev/null &
