#!/bin/bash
# The logic to stop your application should be put in this script.

# this is an example
# -------------------------
# source $OPENSHIFT_CARTRIDGE_SDK_BASH
# if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]
# then
#     client_result "Application is already stopped"
# else
#     kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
# fi

# this is another
# -------------------------
# The logic to stop your application should be put in this script.
#if [[ -z "$OPENSHIFT_INTERNAL_IP" ]]; then export OPENSHIFT_INTERNAL_IP="$OPENSHIFT_DIY_IP"; fi
#if [[ -z "$OPENSHIFT_INTERNAL_PORT" ]]; then export OPENSHIFT_INTERNAL_PORT="$OPENSHIFT_DIY_PORT"; fi
#wget http://${OPENSHIFT_INTERNAL_IP}:${OPENSHIFT_INTERNAL_PORT}?action=stop