CREATE TABLE Shop (
	id BIGINT IDENTITY PRIMARY KEY,
	name VARCHAR(128) UNIQUE NOT NULL
);

CREATE TABLE ProductItem (
	id BIGINT IDENTITY PRIMARY KEY,
	shop_id BIGINT FOREIGN KEY REFERENCES Shop(id),
	detailsUrl VARCHAR(1024) UNIQUE NOT NULL,
	keywordsBundle VARCHAR(1024) NOT NULL,
	priceInCent BIGINT NOT NULL
);

CREATE TABLE Search (
	id BIGINT IDENTITY PRIMARY KEY,
	search VARCHAR(1024) UNIQUE NOT NULL,
	lastTime TIMESTAMP NOT NULL,
	times INTEGER NOT NULL,
	resultCount INTEGER NOT NULL
);

