CREATE TABLE Shop (
	id BIGINT IDENTITY PRIMARY KEY,
	name VARCHAR(128) UNIQUE
);

CREATE TABLE ProductItem (
	id BIGINT IDENTITY PRIMARY KEY,
	shop_id BIGINT FOREIGN KEY REFERENCES Shop(id),
	detailsUrl VARCHAR(1024) NOT NULL,
	keywordsBundle VARCHAR(1024) NOT NULL,
	priceInCent BIGINT NOT NULL
);
